server:
  port: 8090

spring:
  profiles:
      active: local
  application:
    name: DishService
  cloud:
    aws:
      region:
        static: ap-southeast-2
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: orderhere
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/orderhere

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql


resilience4j:
  retry:
    instances:
      healthCheck:
        maxAttempts: 10
        waitDuration: 100ms
  circuitbreaker:
    instances:
      healthCheck:
        slidingWindowSize: 50
        failureRateThreshold: 80
  ratelimiter:
    instances:
      healthCheck:
        limitForPeriod: 1000
        timeoutDuration: 1s
  bulkhead:
    instances:
      healthCheck:
        maxConcurrentCalls: 500
        maxWaitDuration: 500ms

storage:
  bucketName: my-bucket
  url: http://127.0.0.1:9000